
pulseWidthList=[...
                200,200;...
                200,200;...
                200,200;...
                200,200;...
                200,200;...
                ];
            
pulseAmpList=[  ...
                1,1;...
                5,5;...
                10,10;...
                20,20;...
                50,50;...
                ];

% interpulseList=[100,200,300,400,500];
interpulseList=[250];
% prefix='Saline_parameterGridTesting_FastSettle_';
% folder='C:\data\stimTesting\';
prefix='Han_oldAmp_Attenuation_2ndPlug_';
folder='C:\data\Han\stimrecord\';
chanList=[65:4:96,64];
for m=1:numel(interpulseList)
    for j=1:size(pulseAmpList,1)
        pWidth1=pulseWidthList(j,1)%in us
        amp1=pulseAmpList(j,1)%in uA
        pWidth2=pulseWidthList(j,2)%in us
        amp2=pulseAmpList(j,2)%in uA
        interpulse=interpulseList(m)
        testStim
    end
end
        